language: python

sudo: false

python:
  - "3.5"

install:
  - pip install tox-travis

env:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=py36
    - TOX_ENV=py37
    - TOX_ENV=format

script:
    - tox -e $TOX_ENV